import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MealsService } from '../../services/meals.service';
import { PatientService } from '../../services/patient.service';
import { Meal } from '../../models/meal.model';
import { LTCPatient } from '../../models/ltc-patient.model';
import { FormsModule } from '@angular/forms';

export interface MealAssignment {
  id: string;
  dayId: string;
  lunchMeals: any[];
  dinnerMeals: any[];
  selectedLunchMeals: number[];
  selectedDinnerMeals: number[];
}

@Component({
  selector: 'app-add-patient',
  imports: [CommonModule, FormsModule],
  templateUrl: './add-patient.component.html',
  styleUrl: './add-patient.component.scss',
})
export class AddPatientComponent implements OnInit {
  
  // Form data properties
  roomNumber: string = '';
  bedNumber: string = '';
  age: number | null = null;
  sex: string = '';
  height: number | null = null;
  weight: number | null = null;
  activityLevel: string = '';
  dietaryRestrictions: string = '';
  
  mealAssignments: MealAssignment[] = [];
  availableDays = [
    { value: '1', label: 'Day 1' },
    { value: '2', label: 'Day 2' },
    { value: '3', label: 'Day 3' },
    { value: '4', label: 'Day 4' },
    { value: '5', label: 'Day 5' },
    { value: '6', label: 'Day 6' },
    { value: '7', label: 'Day 7' },
    { value: '8', label: 'Day 8' },
    { value: '9', label: 'Day 9' },
    { value: '10', label: 'Day 10' },
    { value: '11', label: 'Day 11' },
    { value: '12', label: 'Day 12' },
    { value: '13', label: 'Day 13' },
    { value: '14', label: 'Day 14' }
  ];
  allMeals: Meal[] = [];

  // Form state
  isSubmitting: boolean = false;
  submitError: string = '';

  constructor(
    private mealsService: MealsService,
    private patientService: PatientService
  ) {}

  ngOnInit(): void {
    // Load all meals on component initialization
    this.loadMeals();
    // Initialize with one assignment
    this.addMealAssignment();
  }

  private loadMeals(): void {
    this.mealsService.getMeals().subscribe({
      next: (meals) => {
        console.log('Meals Response:', meals);
        this.allMeals = meals;
      },
      error: (error) => {
        console.error('Error fetching meals:', error);
      }
    });
  }

  addMealAssignment(): void {
    const newAssignment: MealAssignment = {
      id: this.generateId(),
      dayId: '',
      lunchMeals: [],
      dinnerMeals: [],
      selectedLunchMeals: [],
      selectedDinnerMeals: []
    };
    
    this.mealAssignments.push(newAssignment);
  }

  removeMealAssignment(index: number): void {
    if (this.mealAssignments.length > 1) {
      this.mealAssignments.splice(index, 1);
    }
  }

  onDayChange(event: any, assignmentIndex: number): void {
    const dayId = event.target.value;
    const assignment = this.mealAssignments[assignmentIndex];
    
    assignment.dayId = dayId;
    assignment.selectedLunchMeals = [];
    assignment.selectedDinnerMeals = [];
    
    // Load meals for this day
    this.loadMealsForDay(dayId, assignmentIndex);
  }

  onMealSelection(mealType: 'lunch' | 'dinner', meal: any, event: any, assignmentIndex: number): void {
    const assignment = this.mealAssignments[assignmentIndex];
    const mealId = meal.id;
    
    if (mealType === 'lunch') {
      if (event.target.checked) {
        assignment.selectedLunchMeals.push(mealId);
      } else {
        assignment.selectedLunchMeals = assignment.selectedLunchMeals.filter(id => id !== mealId);
      }
    } else {
      if (event.target.checked) {
        assignment.selectedDinnerMeals.push(mealId);
      } else {
        assignment.selectedDinnerMeals = assignment.selectedDinnerMeals.filter(id => id !== mealId);
      }
    }
  }

  trackByAssignment(index: number, assignment: MealAssignment): string {
    return assignment.id;
  }

  private generateId(): string {
    return Date.now().toString() + Math.random().toString(36).substr(2, 9);
  }

  private loadMealsForDay(dayId: string, assignmentIndex: number): void {
    const assignment = this.mealAssignments[assignmentIndex];
    assignment.lunchMeals = this.allMeals.filter(meal => 
      meal.day_cycle.toString() === dayId && meal.meal_time === '午餐'
    );
    assignment.dinnerMeals = this.allMeals.filter(meal => 
      meal.day_cycle.toString() === dayId && meal.meal_time === '晚餐'
    );

    console.log(`Lunch meals for day ${dayId}:`, assignment.lunchMeals);
    console.log(`Dinner meals for day ${dayId}:`, assignment.dinnerMeals);
  }

  submitForm(): void {
    // Reset form state
    this.isSubmitting = true;
    this.submitError = '';

    try {
      // Validate form data
      if (!this.validateForm()) {
        this.isSubmitting = false;
        return;
      }

      // Create LTC patient object (excluding id as it's auto-generated)
      const ltcPatient: LTCPatient = {
        id: 0, // Placeholder ID, as it will be auto-generated by the backend
        room_number: this.roomNumber,
        bed_number: this.bedNumber,
        age: this.age || 0,
        sex: this.sex,
        height_cm: this.height || 0,
        weight_kg: this.weight || 0,
        activity_level: this.activityLevel
      };

      console.log('Submitting LTC Patient:', ltcPatient);

      // Submit to service
      this.patientService.postLTCPatient(ltcPatient).subscribe({
        next: (response) => {
          console.log('Patient created successfully:', response);
          console.log('Current meal assignments: ', this.mealAssignments);
          this.isSubmitting = false;
          
          // Show success message
          alert('Patient added successfully!');
          
          // Clear form after successful submission
          this.clearForm();
        },
        error: (error) => {
          console.error('Error creating patient:', error);
          this.isSubmitting = false;
          this.submitError = 'Failed to create patient. Please try again.';
          
          // Show error message to user
          alert(`Error: ${error.message || 'Failed to create patient'}`);
        }
      });

    } catch (error) {
      console.error('Form submission error:', error);
      this.isSubmitting = false;
      this.submitError = 'An unexpected error occurred.';
      alert('An unexpected error occurred. Please try again.');
    }
  }

  private validateForm(): boolean {
    // Required field validation
    if (!this.roomNumber.trim()) {
      alert('Room Number is required');
      return false;
    }

    if (!this.bedNumber.trim()) {
      alert('Bed Number is required');
      return false;
    }

    // Basic validation for numeric fields
    if (this.age !== null && this.age <= 0) {
      alert('Age must be a positive number');
      return false;
    }

    if (this.height !== null && this.height <= 0) {
      alert('Height must be a positive number');
      return false;
    }

    if (this.weight !== null && this.weight <= 0) {
      alert('Weight must be a positive number');
      return false;
    }

    return true;
  }

  private processMealAssignments(): any[] {
    return this.mealAssignments
      .filter(assignment => 
        assignment.dayId && 
        (assignment.selectedLunchMeals.length > 0 || assignment.selectedDinnerMeals.length > 0)
      )
      .map(assignment => ({
        day_cycle: parseInt(assignment.dayId),
        lunch_meal_ids: assignment.selectedLunchMeals,
        dinner_meal_ids: assignment.selectedDinnerMeals
      }));
  }

  clearForm(): void {
    // Reset form data
    this.roomNumber = '';
    this.bedNumber = '';
    this.age = null;
    this.sex = '';
    this.height = null;
    this.weight = null;
    this.activityLevel = '';
    this.dietaryRestrictions = '';

    // Reset meal assignments
    this.mealAssignments = [];
    this.addMealAssignment();

    // Reset form state
    this.isSubmitting = false;
    this.submitError = '';

    console.log('Form cleared');
  }
}
